default: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  database: lazy_time_reporting_development
  <<: *defaults

test:
  database: lazy_time_reporting_test
  <<: *defaults

production:
  database: lazy_time_reporting_production
  <<: *defaults
